#!/bin/bash
#
# This isn't really ack, of course, but it's git grep with Perl regexps and
# auto-opening files in vim with the search prerun.
#
# Alternatively, just set these git aliases:
#
#   ack     = "grep --perl-regexp -i --break --heading --line-number"
#   viack   = "grep --perl-regexp -i --open-files-in-pager=vi"
#
git grep --perl-regexp --open-files-in-pager=vi "$@"
